<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maktab.Models\Maktab.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MaktabDataContracts">
      <HintPath>..\libraries\MaktabDataContracts\MaktabDataContracts.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
