//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktab.Consumer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaktabResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaktabResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maktab.Consumer.Localization.MaktabResources", typeof(MaktabResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Group.
        /// </summary>
        public static string Academic_Group {
            get {
                return ResourceManager.GetString("Academic_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Levels.
        /// </summary>
        public static string Academic_Levels {
            get {
                return ResourceManager.GetString("Academic_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active tax payer.
        /// </summary>
        public static string Active_Tax_Payer {
            get {
                return ResourceManager.GetString("Active_Tax_Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active tax credit recipient.
        /// </summary>
        public static string Active_TaxCredit_Recipient {
            get {
                return ResourceManager.GetString("Active_TaxCredit_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string Add_Address {
            get {
                return ResourceManager.GetString("Add_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child.
        /// </summary>
        public static string Add_Child {
            get {
                return ResourceManager.GetString("Add_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string Add_Contact {
            get {
                return ResourceManager.GetString("Add_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Emergency Contact.
        /// </summary>
        public static string Add_Emergency_Contact {
            get {
                return ResourceManager.GetString("Add_Emergency_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extended Info.
        /// </summary>
        public static string Add_Extended_Info {
            get {
                return ResourceManager.GetString("Add_Extended_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Home Address.
        /// </summary>
        public static string Add_Home_Address {
            get {
                return ResourceManager.GetString("Add_Home_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RL 24.
        /// </summary>
        public static string Add_RL24 {
            get {
                return ResourceManager.GetString("Add_RL24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SIN.
        /// </summary>
        public static string Add_SIN {
            get {
                return ResourceManager.GetString("Add_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Spouse.
        /// </summary>
        public static string Add_Spouse {
            get {
                return ResourceManager.GetString("Add_Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment No.
        /// </summary>
        public static string Address_Apartment_No {
            get {
                return ResourceManager.GetString("Address_Apartment_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number.
        /// </summary>
        public static string Address_Apartment_Number {
            get {
                return ResourceManager.GetString("Address_Apartment_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        public static string Address_Details {
            get {
                return ResourceManager.GetString("Address_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Address_Line_1 {
            get {
                return ResourceManager.GetString("Address_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Address_Line_2 {
            get {
                return ResourceManager.GetString("Address_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string Address_Type {
            get {
                return ResourceManager.GetString("Address_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit No.
        /// </summary>
        public static string Address_Unit_No {
            get {
                return ResourceManager.GetString("Address_Unit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Number.
        /// </summary>
        public static string Address_Unit_Number {
            get {
                return ResourceManager.GetString("Address_Unit_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        public static string Amount_Due {
            get {
                return ResourceManager.GetString("Amount_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string Amount_Paid {
            get {
                return ResourceManager.GetString("Amount_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICC Maktab.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available courses.
        /// </summary>
        public static string Available_Courses {
            get {
                return ResourceManager.GetString("Available_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string Back_To_Dashboard {
            get {
                return ResourceManager.GetString("Back_To_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Enrollment.
        /// </summary>
        public static string Confirm_Enrollment {
            get {
                return ResourceManager.GetString("Confirm_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string Contact_Type {
            get {
                return ResourceManager.GetString("Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends on {0}.
        /// </summary>
        public static string Course_Ends_Date_Variable {
            get {
                return ResourceManager.GetString("Course_Ends_Date_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Outline.
        /// </summary>
        public static string Course_Outline {
            get {
                return ResourceManager.GetString("Course_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming — Starts {0}.
        /// </summary>
        public static string Course_Upcoming_Starts_Date_Variable {
            get {
                return ResourceManager.GetString("Course_Upcoming_Starts_Date_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Create_New_Account {
            get {
                return ResourceManager.GetString("Create_New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Date_End {
            get {
                return ResourceManager.GetString("Date_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Date_Start {
            get {
                return ResourceManager.GetString("Date_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daycare.
        /// </summary>
        public static string Daycare {
            get {
                return ResourceManager.GetString("Daycare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daycare Discount.
        /// </summary>
        public static string Daycare_Discount {
            get {
                return ResourceManager.GetString("Daycare_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daycare Fee.
        /// </summary>
        public static string Daycare_Fee {
            get {
                return ResourceManager.GetString("Daycare_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Another.
        /// </summary>
        public static string Enroll_Another {
            get {
                return ResourceManager.GetString("Enroll_Another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Child.
        /// </summary>
        public static string Enroll_Child {
            get {
                return ResourceManager.GetString("Enroll_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll now.
        /// </summary>
        public static string Enroll_Now {
            get {
                return ResourceManager.GetString("Enroll_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled Courses.
        /// </summary>
        public static string Enrolled_Courses {
            get {
                return ResourceManager.GetString("Enrolled_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string Enrollment {
            get {
                return ResourceManager.GetString("Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Details.
        /// </summary>
        public static string Enrollment_Details {
            get {
                return ResourceManager.GetString("Enrollment_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Failed.
        /// </summary>
        public static string Enrollment_Failed {
            get {
                return ResourceManager.GetString("Enrollment_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Successful.
        /// </summary>
        public static string Enrollment_Successful {
            get {
                return ResourceManager.GetString("Enrollment_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments.
        /// </summary>
        public static string Enrollments {
            get {
                return ResourceManager.GetString("Enrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Courses.
        /// </summary>
        public static string FeaturedCourses {
            get {
                return ResourceManager.GetString("FeaturedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Payment.
        /// </summary>
        public static string Fee_Payment {
            get {
                return ResourceManager.GetString("Fee_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address.
        /// </summary>
        public static string Home_Address {
            get {
                return ResourceManager.GetString("Home_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute.
        /// </summary>
        public static string Institute {
            get {
                return ResourceManager.GetString("Institute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our wide range of courses and programs.
        /// </summary>
        public static string MainPage_Description {
            get {
                return ResourceManager.GetString("MainPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ICC Maktab.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Number already exists.
        /// </summary>
        public static string Msg_Error_Add_Child_RAMQ_Already_Added {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Child_RAMQ_Already_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child can not be registered with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Add_Child_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Child_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact can not be added with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Add_Contact_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Contact_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving extended info. please try in few moments.
        /// </summary>
        public static string Msg_Error_Add_ExtendedInfo_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_ExtendedInfo_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add home address.
        /// </summary>
        public static string Msg_Error_Add_Home_Address {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Home_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address type.
        /// </summary>
        public static string Msg_Error_Address_No_AddressType {
            get {
                return ResourceManager.GetString("Msg_Error_Address_No_AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address assignee.
        /// </summary>
        public static string Msg_Error_Address_No_Assignee {
            get {
                return ResourceManager.GetString("Msg_Error_Address_No_Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can not be removed at the moment, please try in few minutes.
        /// </summary>
        public static string Msg_Error_Address_Removed {
            get {
                return ResourceManager.GetString("Msg_Error_Address_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving address please try in few moments.
        /// </summary>
        public static string Msg_Error_Address_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Address_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child can not be removed. please try in few moments.
        /// </summary>
        public static string Msg_Error_Child_Not_Removed {
            get {
                return ResourceManager.GetString("Msg_Error_Child_Not_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete step {0}.
        /// </summary>
        public static string Msg_Error_Complete_Step_Number {
            get {
                return ResourceManager.GetString("Msg_Error_Complete_Step_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact can not be added with system. Please try in few moments.
        /// </summary>
        public static string Msg_Error_Contact_Not_Added {
            get {
                return ResourceManager.GetString("Msg_Error_Contact_Not_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        public static string Msg_Error_Email_Address_Invalid {
            get {
                return ResourceManager.GetString("Msg_Error_Email_Address_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email provided is already registered with system. Please contact support.
        /// </summary>
        public static string Msg_Error_Email_Already_Registered {
            get {
                return ResourceManager.GetString("Msg_Error_Email_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid email.
        /// </summary>
        public static string Msg_Error_Email_Not_Valid {
            get {
                return ResourceManager.GetString("Msg_Error_Email_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments can not be added. Please try in a moment or contact support.
        /// </summary>
        public static string Msg_Error_Enrollment_Not_Added {
            get {
                return ResourceManager.GetString("Msg_Error_Enrollment_Not_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code can not be validated.
        /// </summary>
        public static string Msg_Error_Invalid_Code {
            get {
                return ResourceManager.GetString("Msg_Error_Invalid_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string Msg_Error_New_Password_Not_Match {
            get {
                return ResourceManager.GetString("Msg_Error_New_Password_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address Id.
        /// </summary>
        public static string Msg_Error_No_Address_Id {
            get {
                return ResourceManager.GetString("Msg_Error_No_Address_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid family id.
        /// </summary>
        public static string Msg_Error_No_Family_Id {
            get {
                return ResourceManager.GetString("Msg_Error_No_Family_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any payment transactions yet. Once you enroll in a course, your transactions will appear here.
        /// </summary>
        public static string Msg_Error_No_Payment_Tranaction {
            get {
                return ResourceManager.GetString("Msg_Error_No_Payment_Tranaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all child have valid group assigned.
        /// </summary>
        public static string Msg_Error_Not_All_Child_Valid_Group {
            get {
                return ResourceManager.GetString("Msg_Error_Not_All_Child_Valid_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string Msg_Error_Phone_Number_Invalid {
            get {
                return ResourceManager.GetString("Msg_Error_Phone_Number_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment can not be removed at the moment, please try in few minutes.
        /// </summary>
        public static string Msg_Error_Remove_Enrollment {
            get {
                return ResourceManager.GetString("Msg_Error_Remove_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was not processed. Please retry in few moments.
        /// </summary>
        public static string Msg_Error_Request_Not_Processed {
            get {
                return ResourceManager.GetString("Msg_Error_Request_Not_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can not be registered with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Spouse_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Spouse_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use different new password.
        /// </summary>
        public static string Msg_Error_Use_Diffent_New_Password {
            get {
                return ResourceManager.GetString("Msg_Error_Use_Diffent_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add child to start enrollments.
        /// </summary>
        public static string Msg_Info_Add_Children_To_Enroll {
            get {
                return ResourceManager.GetString("Msg_Info_Add_Children_To_Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining amount to pay.
        /// </summary>
        public static string Msg_Info_Amount_Due {
            get {
                return ResourceManager.GetString("Msg_Info_Amount_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount paid so far.
        /// </summary>
        public static string Msg_Info_Amount_Paid {
            get {
                return ResourceManager.GetString("Msg_Info_Amount_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password.
        /// </summary>
        public static string Msg_Info_Choose_Strong_Password {
            get {
                return ResourceManager.GetString("Msg_Info_Choose_Strong_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter code.
        /// </summary>
        public static string Msg_Info_Enter_Code {
            get {
                return ResourceManager.GetString("Msg_Info_Enter_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter code sent in your email.
        /// </summary>
        public static string Msg_Info_Enter_Code_Email {
            get {
                return ResourceManager.GetString("Msg_Info_Enter_Code_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and track your course payment transactions.
        /// </summary>
        public static string Msg_Info_Manage_Course_Transaction_Payments {
            get {
                return ResourceManager.GetString("Msg_Info_Manage_Course_Transaction_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address selected.
        /// </summary>
        public static string Msg_Info_No_Address_Selected {
            get {
                return ResourceManager.GetString("Msg_Info_No_Address_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups found for this course.
        /// </summary>
        public static string Msg_Info_No_Course_Groups_Found {
            get {
                return ResourceManager.GetString("Msg_Info_No_Course_Groups_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modules available.
        /// </summary>
        public static string Msg_Info_No_Course_Modules {
            get {
                return ResourceManager.GetString("Msg_Info_No_Course_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Enrollments.
        /// </summary>
        public static string Msg_Info_No_Enrollment {
            get {
                return ResourceManager.GetString("Msg_Info_No_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique payment code for this transaction.
        /// </summary>
        public static string Msg_Info_Payment_Code {
            get {
                return ResourceManager.GetString("Msg_Info_Payment_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide old password.
        /// </summary>
        public static string Msg_Info_Provide_Old_Password {
            get {
                return ResourceManager.GetString("Msg_Info_Provide_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        public static string Msg_Info_Repeat_Password {
            get {
                return ResourceManager.GetString("Msg_Info_Repeat_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more enrollment groups.
        /// </summary>
        public static string Msg_Info_Select_One_More_Enrollment_Group {
            get {
                return ResourceManager.GetString("Msg_Info_Select_One_More_Enrollment_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount across all courses.
        /// </summary>
        public static string Msg_Info_Total_Amount {
            get {
                return ResourceManager.GetString("Msg_Info_Total_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Msg_Info_Value_Is_Required {
            get {
                return ResourceManager.GetString("Msg_Info_Value_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &quot;Other&quot; in drop down and set zero in donation section.
        /// </summary>
        public static string Msg_Info_Zeffy_Payment_donation_section {
            get {
                return ResourceManager.GetString("Msg_Info_Zeffy_Payment_donation_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use following payment code and email in mandatory fields on Zeffy payment.
        /// </summary>
        public static string Msg_Info_Zeffy_Payment_Mandatory_Fields {
            get {
                return ResourceManager.GetString("Msg_Info_Zeffy_Payment_Mandatory_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Msg_Initializing {
            get {
                return ResourceManager.GetString("Msg_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading course details....
        /// </summary>
        public static string Msg_Loading_Course_Details {
            get {
                return ResourceManager.GetString("Msg_Loading_Course_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Msg_Processing {
            get {
                return ResourceManager.GetString("Msg_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove address?.
        /// </summary>
        public static string Msg_Question_Remove_Address {
            get {
                return ResourceManager.GetString("Msg_Question_Remove_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove enrollment?.
        /// </summary>
        public static string Msg_Question_Remove_Enrollment {
            get {
                return ResourceManager.GetString("Msg_Question_Remove_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove {0} ?.
        /// </summary>
        public static string Msg_Question_Remove_Variable {
            get {
                return ResourceManager.GetString("Msg_Question_Remove_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments have been added successfully.
        /// </summary>
        public static string Msg_Success_Add_Enrollment {
            get {
                return ResourceManager.GetString("Msg_Success_Add_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been added successfully.
        /// </summary>
        public static string Msg_Success_Address_Added {
            get {
                return ResourceManager.GetString("Msg_Success_Address_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Remove successfully!.
        /// </summary>
        public static string Msg_Success_Address_Removed {
            get {
                return ResourceManager.GetString("Msg_Success_Address_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child has been added.
        /// </summary>
        public static string Msg_Success_Child_Added {
            get {
                return ResourceManager.GetString("Msg_Success_Child_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been enrolled in {1}.
        /// </summary>
        public static string Msg_Success_Child_Enrolled_Course_Variable {
            get {
                return ResourceManager.GetString("Msg_Success_Child_Enrolled_Course_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child has been Remove successfully!.
        /// </summary>
        public static string Msg_Success_Child_Removed {
            get {
                return ResourceManager.GetString("Msg_Success_Child_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact has been added.
        /// </summary>
        public static string Msg_Success_Contact_Added {
            get {
                return ResourceManager.GetString("Msg_Success_Contact_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0} for registration with {1}..
        /// </summary>
        public static string Msg_Success_Parent_Registration {
            get {
                return ResourceManager.GetString("Msg_Success_Parent_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Remove successfully.
        /// </summary>
        public static string Msg_Success_Remove_Enrollment {
            get {
                return ResourceManager.GetString("Msg_Success_Remove_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been linked.
        /// </summary>
        public static string Msg_Success_Spouse_Save {
            get {
                return ResourceManager.GetString("Msg_Success_Spouse_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been linked.
        /// </summary>
        public static string Msg_Sucess_User_Linked {
            get {
                return ResourceManager.GetString("Msg_Sucess_User_Linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string Msg_Validation_New_Password {
            get {
                return ResourceManager.GetString("Msg_Validation_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is required!.
        /// </summary>
        public static string Msg_Validation_Old_Password {
            get {
                return ResourceManager.GetString("Msg_Validation_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid family identifier.
        /// </summary>
        public static string Msg_Warning_Provide_Family_Id {
            get {
                return ResourceManager.GetString("Msg_Warning_Provide_Family_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password.
        /// </summary>
        public static string New_Password_HelperText {
            get {
                return ResourceManager.GetString("New_Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Course Found.
        /// </summary>
        public static string No_Course_Found {
            get {
                return ResourceManager.GetString("No_Course_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transactions.
        /// </summary>
        public static string No_Transaction {
            get {
                return ResourceManager.GetString("No_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide old password.
        /// </summary>
        public static string Old_Password_HelperText {
            get {
                return ResourceManager.GetString("Old_Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Health Conditions.
        /// </summary>
        public static string Other_Health__Conditions {
            get {
                return ResourceManager.GetString("Other_Health _Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        public static string Parent_Registration_Success {
            get {
                return ResourceManager.GetString("Parent_Registration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Paid.
        /// </summary>
        public static string Partially_Paid {
            get {
                return ResourceManager.GetString("Partially_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Password_Forgot {
            get {
                return ResourceManager.GetString("Password_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string Pay_Now {
            get {
                return ResourceManager.GetString("Pay_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Code.
        /// </summary>
        public static string Payment_Code {
            get {
                return ResourceManager.GetString("Payment_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string Payment_Details {
            get {
                return ResourceManager.GetString("Payment_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Payment Transactions.
        /// </summary>
        public static string Payment_Transaction {
            get {
                return ResourceManager.GetString("Payment_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0}%.
        /// </summary>
        public static string Progress_Variable {
            get {
                return ResourceManager.GetString("Progress_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid credentials.
        /// </summary>
        public static string Provide_Valid_Credentials {
            get {
                return ResourceManager.GetString("Provide_Valid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Expiry.
        /// </summary>
        public static string RAMQ_Expiry {
            get {
                return ResourceManager.GetString("RAMQ_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Number.
        /// </summary>
        public static string RAMQ_Number {
            get {
                return ResourceManager.GetString("RAMQ_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Fee.
        /// </summary>
        public static string Registration_Fee {
            get {
                return ResourceManager.GetString("Registration_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration open.
        /// </summary>
        public static string Registration_Open {
            get {
                return ResourceManager.GetString("Registration_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship with children.
        /// </summary>
        public static string Relashion_With_Children {
            get {
                return ResourceManager.GetString("Relashion_With_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        public static string Repeat_Password_HelperText {
            get {
                return ResourceManager.GetString("Repeat_Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Enrollment.
        /// </summary>
        public static string Review_Enrollment {
            get {
                return ResourceManager.GetString("Review_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search courses.
        /// </summary>
        public static string Search_Courses {
            get {
                return ResourceManager.GetString("Search_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Child.
        /// </summary>
        public static string Select_Child {
            get {
                return ResourceManager.GetString("Select_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course.
        /// </summary>
        public static string Select_Course {
            get {
                return ResourceManager.GetString("Select_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Enrollment Group.
        /// </summary>
        public static string Select_Enrollment_Group {
            get {
                return ResourceManager.GetString("Select_Enrollment_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code again.
        /// </summary>
        public static string Send_Code_Again {
            get {
                return ResourceManager.GetString("Send_Code_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending code.
        /// </summary>
        public static string Sending_Code {
            get {
                return ResourceManager.GetString("Sending_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN number.
        /// </summary>
        public static string SIN_Number {
            get {
                return ResourceManager.GetString("SIN_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Exploring.
        /// </summary>
        public static string Start_Exploring {
            get {
                return ResourceManager.GetString("Start_Exploring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0}.
        /// </summary>
        public static string Step_Number {
            get {
                return ResourceManager.GetString("Step_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax info.
        /// </summary>
        public static string Tax_Info {
            get {
                return ResourceManager.GetString("Tax_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string Total_Amount {
            get {
                return ResourceManager.GetString("Total_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Daycare.
        /// </summary>
        public static string Use_Daycare {
            get {
                return ResourceManager.GetString("Use_Daycare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Code.
        /// </summary>
        public static string Validate_Code {
            get {
                return ResourceManager.GetString("Validate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string View_Details {
            get {
                return ResourceManager.GetString("View_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Courses.
        /// </summary>
        public static string ViewAllCourses {
            get {
                return ResourceManager.GetString("ViewAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string Welcome_User {
            get {
                return ResourceManager.GetString("Welcome_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
