//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktab.Consumer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaktabResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaktabResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maktab.Consumer.Localization.MaktabResources", typeof(MaktabResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Group.
        /// </summary>
        public static string Academic_Group {
            get {
                return ResourceManager.GetString("Academic_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active tax payer.
        /// </summary>
        public static string Active_Tax_Payer {
            get {
                return ResourceManager.GetString("Active_Tax_Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string Add_Address {
            get {
                return ResourceManager.GetString("Add_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SIN.
        /// </summary>
        public static string Add_SIN {
            get {
                return ResourceManager.GetString("Add_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number.
        /// </summary>
        public static string Address_Apartment_Number {
            get {
                return ResourceManager.GetString("Address_Apartment_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Address_Line_1 {
            get {
                return ResourceManager.GetString("Address_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Address_Line_2 {
            get {
                return ResourceManager.GetString("Address_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Number.
        /// </summary>
        public static string Address_Unit_Number {
            get {
                return ResourceManager.GetString("Address_Unit_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICC Maktab.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string Contact_Type {
            get {
                return ResourceManager.GetString("Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Create_New_Account {
            get {
                return ResourceManager.GetString("Create_New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Courses.
        /// </summary>
        public static string FeaturedCourses {
            get {
                return ResourceManager.GetString("FeaturedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address.
        /// </summary>
        public static string Home_Address {
            get {
                return ResourceManager.GetString("Home_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our wide range of courses and programs.
        /// </summary>
        public static string MainPage_Description {
            get {
                return ResourceManager.GetString("MainPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ICC Maktab.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Number already exists.
        /// </summary>
        public static string Msg_Error_Add_Child_RAMQ_Already_Added {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Child_RAMQ_Already_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child can not be registered with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Add_Child_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Child_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact can not be added with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Add_Contact_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_Contact_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving extended info. please try in few moments.
        /// </summary>
        public static string Msg_Error_Add_ExtendedInfo_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Add_ExtendedInfo_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address type.
        /// </summary>
        public static string Msg_Error_Address_No_AddressType {
            get {
                return ResourceManager.GetString("Msg_Error_Address_No_AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address assignee.
        /// </summary>
        public static string Msg_Error_Address_No_Assignee {
            get {
                return ResourceManager.GetString("Msg_Error_Address_No_Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can not be removed at the moment, please try in few minutes.
        /// </summary>
        public static string Msg_Error_Address_Removed {
            get {
                return ResourceManager.GetString("Msg_Error_Address_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving address please try in few moments.
        /// </summary>
        public static string Msg_Error_Address_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Address_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        public static string Msg_Error_Email_Address_Invalid {
            get {
                return ResourceManager.GetString("Msg_Error_Email_Address_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email provided is already registered with system. Please contact support.
        /// </summary>
        public static string Msg_Error_Email_Already_Registered {
            get {
                return ResourceManager.GetString("Msg_Error_Email_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid address Id.
        /// </summary>
        public static string Msg_Error_No_Address_Id {
            get {
                return ResourceManager.GetString("Msg_Error_No_Address_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid family id.
        /// </summary>
        public static string Msg_Error_No_Family_Id {
            get {
                return ResourceManager.GetString("Msg_Error_No_Family_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string Msg_Error_Phone_Number_Invalid {
            get {
                return ResourceManager.GetString("Msg_Error_Phone_Number_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can not be registered with system. Please try again in few minutes.
        /// </summary>
        public static string Msg_Error_Spouse_Save {
            get {
                return ResourceManager.GetString("Msg_Error_Spouse_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Msg_Info_Value_Is_Required {
            get {
                return ResourceManager.GetString("Msg_Info_Value_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Msg_Initializing {
            get {
                return ResourceManager.GetString("Msg_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Msg_Processing {
            get {
                return ResourceManager.GetString("Msg_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove address.
        /// </summary>
        public static string Msg_Question_Remove_Address {
            get {
                return ResourceManager.GetString("Msg_Question_Remove_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Remove successfully!.
        /// </summary>
        public static string Msg_Success_Address_Removed {
            get {
                return ResourceManager.GetString("Msg_Success_Address_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child has been added.
        /// </summary>
        public static string Msg_Success_Child_Added {
            get {
                return ResourceManager.GetString("Msg_Success_Child_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact has been added.
        /// </summary>
        public static string Msg_Success_Contact_Added {
            get {
                return ResourceManager.GetString("Msg_Success_Contact_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been linked.
        /// </summary>
        public static string Msg_Success_Spouse_Save {
            get {
                return ResourceManager.GetString("Msg_Success_Spouse_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Course Found.
        /// </summary>
        public static string No_Course_Found {
            get {
                return ResourceManager.GetString("No_Course_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Health Conditions.
        /// </summary>
        public static string Other_Health__Conditions {
            get {
                return ResourceManager.GetString("Other_Health _Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Password_Forgot {
            get {
                return ResourceManager.GetString("Password_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid credentials.
        /// </summary>
        public static string Provide_Valid_Credentials {
            get {
                return ResourceManager.GetString("Provide_Valid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Expiry.
        /// </summary>
        public static string RAMQ_Expiry {
            get {
                return ResourceManager.GetString("RAMQ_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMQ Number.
        /// </summary>
        public static string RAMQ_Number {
            get {
                return ResourceManager.GetString("RAMQ_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship with children.
        /// </summary>
        public static string Relashion_With_Children {
            get {
                return ResourceManager.GetString("Relashion_With_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN number.
        /// </summary>
        public static string SIN_Number {
            get {
                return ResourceManager.GetString("SIN_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax info.
        /// </summary>
        public static string Tax_Info {
            get {
                return ResourceManager.GetString("Tax_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string View_Details {
            get {
                return ResourceManager.GetString("View_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Courses.
        /// </summary>
        public static string ViewAllCourses {
            get {
                return ResourceManager.GetString("ViewAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string Welcome_User {
            get {
                return ResourceManager.GetString("Welcome_User", resourceCulture);
            }
        }
    }
}
