<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MaktabResources.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.22" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.22" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="MudBlazor.Translations" Version="2.7.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maktab.Core\Maktab.Core.csproj" />
    <ProjectReference Include="..\Maktab.Domain\Maktab.Domain.csproj" />
    <ProjectReference Include="..\Maktab.Infrastructure\Maktab.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MaktabDataContracts">
      <HintPath>..\libraries\MaktabDataContracts\MaktabDataContracts.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Register\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\MaktabResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaktabResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\MaktabResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaktabResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
